# Generated by Django 4.1.2 on 2022-11-30 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='user',
        ),
        migrations.AddField(
            model_name='entry',
            name='poster',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='persons.person'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='emotion',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_description',
            field=models.TextField(default=None),
        ),
    ]
