# Generated by Django 4.1.2 on 2022-12-03 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='netid',
        ),
    ]
