# Generated by Django 4.1.2 on 2022-12-12 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_person_netid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='person',
            name='netid',
        ),
        migrations.RemoveField(
            model_name='person',
            name='pronouns',
        ),
    ]
